version: '3.8'

services:
  dev:
    depends_on:
      - dev-db
    container_name: nest_api_development
    image: nest_api_development:latest
    build:
      context: ./
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - nest-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  dev-db:
    container_name: dev-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db
    networks:
      - nest-network

networks:
  nest-network: